### ISSUE TITLE
update team page

### ISSUE THREAD

**Issue by rahulkumaran** [FreeFlowOrg/FreeFlowOrg.github.io#13]
remove "<" in the team page under jayesh's name xD

**Comment by rahulkumaran** [comment]
@CodHeK @mrsaicharan1 can either of you fix this? xD

**Comment by CodHeK** [comment]
@rahulkumaran what will i get if i successfully fix the bug  ? :p

**Comment by rahulkumaran** [comment]
You get to boast about being an active part of this next level startup :p
